---
title: "University of Alberta Faculty of Engineering Research Output"
author: "Alison Henry"
date: "September 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Install needed packages: bibliometrix, splitstackshape

```{r}
install.packages("bibliometrix", dependencies = TRUE)
install.packages("splitstackshape")
```
## Read in downloaded files and convert to dataframe

```{r}
D <- readFiles("savedrecs1.bib", "savedrecs2.bib", "savedrecs3.bib", "savedrecs4.bib", "savedrecs5.bib", "savedrecs6.bib", "savedrecs7.bib", "savedrecs8.bib", "savedrecs9.bib", "savedrecs10.bib", "savedrecs11.bib", "savedrecs12.bib", "savedrecs13.bib")
M <- convert2df(D, dbsource = "isi", format = "bibtex")
```
## Keep only selected columns: UT, AU, DT, C1, TC, PY
```{r}
mydata <- subset(M, select = c(UT, C1, DT, TC, PY))
```
## Separate authors into sinlge observations
```{r}
tidy_data <- cSplit(mydata, "C1", sep = ";", direction = "long")
```
## Test that there were no unintended drops
```{r}
count <- sum(str_count(mydata$C1, ";"))
ifelse(count + nrow(mydata) == nrow(tidy_data), "No drops", "Warning") 
```
## Remove non-UofA addresses
```{r}
AlbertaData <- tidy_data[grep("UNIV ALBERTA", tidy_data$C1), ]
```
## Identify departmental affiliations
```{r}
depts <- data.frame()
  ```